'use client'
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import { Work_Sans } from 'next/font/google';
import { Poppins } from 'next/font/google';
import { Provider } from "react-redux";
import store from "@/redux/store";
import Head from "next/head";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600'], // Choose the weights you need
});

const workSans = Work_Sans({
  subsets: ['latin'],
  weight: ['400', '700'], 
});

const metadata: Metadata = {
  title: "JOBHUNT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  
    <html lang="en">
      <Head>
        <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.6.0/uicons-thin-straight/css/uicons-thin-straight.css' />
      </Head>
      <body
        className={`${workSans.className} antialiased`}
        >
        <Provider store={store}>
          
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>

  );
}
